### ISSUE TITLE
Lobos does not find backend when using {:datasource xxx} type config

### ISSUE THREAD

**Issue by jsyrjala** [budu/lobos#26]
If I configure lobos to use a connection pool like this

(defn database-handle [dbh](let [connection-pool %28doto %28DataSource.%29
                          %28.setDriverClassName %28dbh :classname%29%29
                          %28.setUrl %28str "jdbc:" %28:subprotocol dbh) ":" (:subname dbh)))
                          (.setUsername (:user dbh))
                          (.setPassword (:password dbh)) )]
    {:datasource connection-pool }
    ))

(open-global (database-handle dbconfig))

I get following stacktrace. The problems is that lobos is assuming that :subprotocol key is available in configuration map. Maybe lobos should autodetect the subprotocol somehow or at least give better error message. The workaround is to define :subprotocol to database configuration map. 

Exception in thread "main" java.io.FileNotFoundException: Could not locate lobos/backends/__init.class or lobos/backends/.clj on classpath:  (NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5440)
    at clojure.lang.Compiler.eval(Compiler.java:5415)
    at clojure.lang.Compiler.eval(Compiler.java:5391)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$null_opt.invoke(main.clj:279)
...

**Comment by jsyrjala** [comment]
This happens at least with Lobos 0.8.0.

**Comment by budu** [comment]
I see, I hadn't tried with a datasource yet. I've just pushed some small improvements which include throwing a better error message for this case and it's available in the latest Clojar snapshot. I'll leave this ticket open as this is just a temporary measure, I'll probably change the compiler code to use the same mechanism as the analyzer which autodetect the subprotocol.

**Comment by budu** [comment]
I've created a new ticket (#31) for a better solution to this issue.
