### ISSUE TITLE
Got exception when rename column

### ISSUE THREAD

**Issue by sunng87** [budu/lobos#36]
I'm not sure if I used it correctly because I didn't find code example for this action. My migration is :

``` clojure
(defmigration add-user-table
  (up []
      (create 
       (table :kusers (integer :id :primary-key :auto-inc)
              (varchar :email 100 :unique)
              (timestamp :next-update)))
      (index :kusers [:email])
      (index :kusers [:next-update]))
  (down []
        (drop (table :kusers))))

(defmigration rename-user-table-timestamp
  (up []
      (alter
       (table :kusers
              (column :next-update :to :last-update))))
  (down []
        (alter
         (table :kusers
                (column :last-update :to :next-update)))))

```

The create action goes right. But I got exception in the second action:

```
rename-user-table-timestamp
Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :build-alter-statement of protocol: #'lobos.schema/Alterable found for class: nil
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:495)
    at lobos.schema$eval980$fn__981$G__971__990.invoke(schema.clj:40)
    at lobos.core$alter_STAR_.doInvoke(core.clj:138)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at lobos.migrations$reify__2337.up(migrations.clj:36)
    at lobos.migration$do_migrations.doInvoke(migration.clj:249)
    at clojure.lang.RestFn.invoke(RestFn.java:470)
    at lobos.core$migrate.doInvoke(core.clj:197)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at user$eval2207.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6465)
    at clojure.lang.Compiler.eval(Compiler.java:6455)
    at clojure.lang.Compiler.eval(Compiler.java:6431)
    at clojure.core$eval.invoke(core.clj:2795)
    at clojure.main$eval_opt.invoke(main.clj:296)
    at clojure.main$initialize.invoke(main.clj:315)
    at clojure.main$null_opt.invoke(main.clj:348)
    at clojure.main$main.doInvoke(main.clj:426)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:405)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:518)
    at clojure.main.main(main.java:37)
```

Anyway, would you please add example for renaming column to your document ? It's a common action and the DSL is difficult to guess :)

**Comment by budu** [comment]
Yeah, sorry about the state of the documentation for alter, I'm working on some new one, but it might take some time before I finish it. Here's an example of how to rename a table:

```
(alter :rename (table :foo (column :a :to :b)))
```

You were only missing the `alter` sub-action (I must say that the doc isn't right in the website, so I'm the one to blame). There's more examples in the alter docstring, try out `(doc alter)` for more information.

**Comment by sunng87** [comment]
Thank you for the example. I have changed my migration to:

``` clojure
(alter :rename
       (table :kusers
              (column :next-update :to :last-update)))
```

But I still got exception:

```
Exception in thread "main" java.lang.NullPointerException
    at clojure.core$name.invoke(core.clj:1488)
    at lobos.backends.mysql$analyze_column.invoke(mysql.clj:66)
    at lobos.backends.mysql$eval2296$fn__2297$fn__2299.invoke(mysql.clj:166)
    at lobos.connectivity$with_spec_connection.invoke(connectivity.clj:143)
    at lobos.backends.mysql$eval2296$fn__2297.invoke(mysql.clj:164)
    at clojure.lang.MultiFn.invoke(MultiFn.java:163)
    at lobos.compiler$eval867$fn__868.invoke(compiler.clj:341)
    at clojure.lang.MultiFn.invoke(MultiFn.java:163)
    at lobos.internal$execute$fn__1782.invoke(internal.clj:62)
    at lobos.connectivity$with_spec_connection.invoke(connectivity.clj:143)
    at lobos.internal$execute.doInvoke(internal.clj:56)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at lobos.core$alter_STAR_.doInvoke(core.clj:138)
    at clojure.lang.RestFn.invoke(RestFn.java:439)
    at lobos.migrations$reify__2337.up(migrations.clj:36)
    at lobos.migration$do_migrations.doInvoke(migration.clj:249)
    at clojure.lang.RestFn.invoke(RestFn.java:470)
    at lobos.core$migrate.doInvoke(core.clj:197)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at user$eval2207.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6465)
    at clojure.lang.Compiler.eval(Compiler.java:6455)
    at clojure.lang.Compiler.eval(Compiler.java:6431)
    at clojure.core$eval.invoke(core.clj:2795)
    at clojure.main$eval_opt.invoke(main.clj:296)
    at clojure.main$initialize.invoke(main.clj:315)
    at clojure.main$null_opt.invoke(main.clj:348)
    at clojure.main$main.doInvoke(main.clj:426)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:405)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:518)
    at clojure.main.main(main.java:37)
```

**Comment by budu** [comment]
That seems to be a bug in the MySQL backend, I'll look at it. In the meantime could you provide me with the version of the driver you're using, this might help me figure it out.

**Comment by sunng87** [comment]
I'm running on 1.0.0-SNAPSHOT from clojars: lobos-1.0.0-20120108.020200-5.jar

**Comment by budu** [comment]
I can't reproduce this bug it seems. I suspect that it's a problem with an old version of the MySQL driver though. I'm using version 5.1.18 of MySQL Connector, could you provide me with the version you are using.

**Comment by sunng87** [comment]
My connector is 5.1.18, and mysql version 5.5.21

I've created a simplified case and it's reproducible on my machine.

``` clojure
(ns lobos.migrations
  (:refer-clojure :exclude [alter drop
                            bigint boolean char double float time])
  (:use (lobos [migration :only [defmigration]]
               core
               schema
               config)))

(defmigration create-test-table
  (up []
      (create
       (table :kk
              (integer :hello))))
  (down []
        (drop (table :kk))))

(defmigration rename-test-table
  (up []
      (alter :rename
             (table :kk
                    (column :hello :to :world))))
  (down []
        (alter :rename
               (table :kk
                      (column :world :to :hello)))))

```

Would you please double check my migration syntax in case that I still have mistake in it.

BTW, I run migration with the lein-lobos plugin.

**Comment by budu** [comment]
I've just fixed the issue, I wasn't catching it in my test as I create and specify the database to be use, while this only happen when a database is specified by default. There's a new snapshot on Clojars.
