### ISSUE TITLE
Unable to resolve symbol

### ISSUE THREAD

**Issue by pallix** [budu/lobos#72]
Hello,

I get an "unable to resolve symbol" when using lobos with the following dependencies:

```
[org.clojure/java.jdbc "0.3.3"]
[lobos "1.0.0-beta1"]
[korma "0.3.2"]
```

```
xception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: *db* in this context, compiling:(lobos/connectivity/jdbc_2.clj:14:1)
    at clojure.lang.Compiler.analyze(Compiler.java:6464)
    at clojure.lang.Compiler.access$100(Compiler.java:38)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6050)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3665)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6012)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler.compile1(Compiler.java:7221)
    at clojure.lang.Compiler.compile(Compiler.java:7292)
    at clojure.lang.RT.compile(RT.java:398)
    at clojure.lang.RT.load(RT.java:438)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at lobos.connectivity$fn__9159.invoke(connectivity.clj:17)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3553)
    at clojure.lang.Compiler.compile1(Compiler.java:7226)
    at clojure.lang.Compiler.compile(Compiler.java:7292)
    at clojure.lang.RT.compile(RT.java:398)
    at clojure.lang.RT.load(RT.java:438)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5528)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at lobos.core$loading__4958__auto__.invoke(core.clj:9)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3553)
    at clojure.lang.Compiler.compile1(Compiler.java:7226)
    at clojure.lang.Compiler.compile1(Compiler.java:7216)
    at clojure.lang.Compiler.compile(Compiler.java:7292)
    at clojure.lang.RT.compile(RT.java:398)
    at clojure.lang.RT.load(RT.java:438)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:619)

```

**Comment by pallix** [comment]
I git checkouted the code and the line at `lobos/connectivity/jdbc_2.clj:14:1` does not compile

**Comment by pallix** [comment]
I think you are doing a wrong assumption with this code:

```
(try
  (require 'lobos.connectivity.jdbc-1)
  (catch Throwable e
    (try
      (require 'lobos.connectivity.jdbc-2)
      (catch Throwable e
        (do
          (ns-unalias 'lobos.connectivity 'sqlint)
          (require 'lobos.connectivity.jdbc-3))))))
```

It seems your are trying to identify some characteristics of the jdbc component dynamically, or to find the good version.

Since some namespaces (jdbc1) throws an exceptions when the import is wrong, you catch them and deal with that.

This does not work when creating a WAR file though, since every namespaces get compiled separately and is packed into the archive.

**Comment by seancorfield** [comment]
You can't trap a compile error with `Throwable` - you need `(catch Exception e ...)` to trap a `RuntimeException`.

**Comment by pallix** [comment]
This won't help when trying to AOT or byte-compile into a WAR the lobos.connectivity.jdbc-1 or lobos.connectivity.jdbc-2 namespaces. Each of this namespace will be separately compile, no?

**Comment by thieman** [comment]
Can we get a release now that this is merged? I'd imagine using Lobos and Korma together is very common, and if so this is causing quite a problem.

**Comment by paomian** [comment]
yes,i use them all,and i get de error message like this,can we get a release now without this bug?

**Comment by dvcrn** [comment]
Another vote for a release. Was searching for a migration system to add to my stack but couldn't figure out why none of the tutorials / guides is working. Turns out this bug was the cause. Using korma as well

**Comment by jarofghosts** [comment]
+1

**Comment by dvcrn** [comment]
While browsing through the issue tracker, I ran into https://github.com/budu/lobos/issues/66. Is this still relevant? Is the project still dead? I'm asking since I'm seeing commits after that ticket has been closed

**Comment by budu** [comment]
More or less, I'm not working on it anymore, but I try to at least merge stuff from time to time. I haven't had the time for doing a new release for a while as I'm short on time and motivation. I'll try to see if I can get this done this evening.

If someone can take over, message me, I could probably transfer the Clojars name to another account and add some collaborators or we can arrange to make a fork official.

**Comment by budu** [comment]
By popular demand, lobos 1.0.0-beta3 has been deployed to Clojars!

**Comment by thieman** [comment]
![](http://i.imgur.com/Gzh71Ku.gif)

**Comment by dvcrn** [comment]
Migrations run smoothly now. Thanks for the release!

**Comment by paomian** [comment]
赞！

**Comment by paomian** [comment]
and then could you change the readme.md from beta1 to beta3
