### ISSUE TITLE
Table 'lobos_migrations' already exists

### ISSUE THREAD

**Issue by pkvov** [budu/lobos#79]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lobos_migrations' already exists

(def db-spec
  {:subprotocol "mysql"
   :subname "//localhost:3306/myyun?zeroDateTimeBehavior=convertToNull"
   :delimiters "`"  ;; very important to mysql. cause the sql syntax error
   :user "xxxx"
   :password "xxxx"})

when i delete ?zeroDateTimeBehavior=convertToNull , everything is ok.

thanks

**Comment by pkvov** [comment]
Exception in thread "main" com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lobos_migrations' already exists, compiling:(/private/var/folders/mk/ngydbzbn71718_nrwbbktgn40000gq/T/form-init14\
54663978847119327.clj:1:142)
        at clojure.lang.Compiler.load(Compiler.java:7142)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lobos_migrations' already exists
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
        at com.mysql.jdbc.Util.getInstance(Util.java:381)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2536)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:734)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at lobos.internal$execute_STAR_$fn__8794.invoke(internal.clj:45)
        at lobos.internal$execute_STAR_.invoke(internal.clj:44)
        at lobos.internal$execute$fn__8803.invoke(internal.clj:65)
        at lobos.connectivity$with_spec_connection.invoke(connectivity.clj:154)
        at lobos.internal$execute.doInvoke(internal.clj:58)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at lobos.migration$create_migrations_table.invoke(migration.clj:204)
        at myyun.db.schema$pending_migrations.doInvoke(schema.clj:16)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at myyun.db.schema$actualized_QMARK_.invoke(schema.clj:22)
        at myyun.handler$init.invoke(handler.clj:43)
        at clojure.lang.Var.invoke(Var.java:375)
        at ring.server.standalone$serve.doInvoke(standalone.clj:93)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at ring.server.leiningen$serve.invoke(leiningen.clj:20)
        at user$eval14845.invoke(form-init1454663978847119327.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        ... 11 more
